#pragma once
#include "Profiling/Trackable.hpp"
#include "Graphics/SpriteAtlas.hpp"
#include "Animation.hpp"
#include "AnimationFrame.hpp"

namespace Cori {
	namespace World {
		namespace Components {
			namespace Entity {
				class QuadAnimator;
			}
		}
	}
	namespace Graphics {
		namespace Internal {
			class AnimationData {
			public:
				AnimationData(const glm::u16vec2 frameSize, std::vector<AnimationFrame> frames) : m_FrameSize(frameSize), m_Frames(std::move(frames)) {}

				glm::u16vec2 m_FrameSize;
				std::vector<AnimationFrame> m_Frames;
			};
		}

		/**
		 * @brief Represents a pack of sprite animations that were loaded from the drive from the pair of an image file and json config.
		 * @details I can load several types of configs: ASEPRITE, CORI_UNIFORM, CORI_VARYING.
		 * \n ASEPRITE: uses the config that is generated by aseprite when extracting the animation, adds extruding to each sprite on animation atlas, all animation frames should be the same resolution.
		 * \n CORI_UNIFORM: uses engine native json config layout to load a pack of animations, adds extruding to each sprite on animation atlas, all animation frames should be the same resolution.
		 * \n Example of the json layout:
		 * ```cpp
		 *  {
		 *    "meta": {
		 *      "frameSizeX": 32,
		 *      "frameSizeY": 32,
		 *      "textureFile": "Atlas.png"
		 *    },
		 *    "animations": [
		 *      {
		 *        "frames": [ { "x": 0, "y": 0, "ms": 100 }, { "x": 32, "y": 0, "ms": 100 }, { "x": 64, "y": 0, "ms": 100 }, { "x": 96, "y": 0, "ms": 100 }, { "x": 128, "y": 0, "ms": 100 }, { "x": 160, "y": 0, "ms": 100 } ]
		 *      },
		 *      {
		 *        "frames": [ { "x": 0, "y": 32, "ms": 100 }, { "x": 32, "y": 32, "ms": 100 }, { "x": 64, "y": 32, "ms": 100 }, { "x": 96, "y": 32, "ms": 100 }, { "x": 128, "y": 32, "ms": 100 }, { "x": 160, "y": 32, "ms": 100 } ]
		 *      },
		 *      {
		 *        "frames": [ { "x": 0, "y": 64, "ms": 100 }, { "x": 32, "y": 64, "ms": 100 }, { "x": 64, "y": 64, "ms": 100 }, { "x": 96, "y": 64, "ms": 100 }, { "x": 128, "y": 64, "ms": 100 }, { "x": 160, "y": 64, "ms": 100 } ]
		 *      }
		 *    ]
		 *  }
		 * ```
		 * Here we load animation from image 'Atlas.png' (path relative to the json config), we load 3 animation each with 6 frames all have frame size of 32x32, x and y pairs is the left upper corner of each animation frame, the lower right corner is calculated based on frameSizeX and frameSizeY.
		 * \n CORI_VARYING: uses engine native json config layout to load a pack of animations, different animations can have different frame size, but at the cost of not adding padding to each frame sprite so texel bleeding can occur, be aware.
		 * \n Example of the json layout:
		 * ```cpp
		 *  {
		 *   "meta": {
		 *     "textureFile": "Atlas.png"
		 *   },
		 *   "animations": [
		 *     {
		 *       "frameSizeX": 32,
		 *       "frameSizeY": 32,
		 *       "frames": [ { "x": 0, "y": 0, "ms": 100 }, { "x": 32, "y": 0, "ms": 100 }, { "x": 64, "y": 0, "ms": 100 }, { "x": 96, "y": 0, "ms": 100 }, { "x": 128, "y": 0, "ms": 100 }, { "x": 160, "y": 0, "ms": 100 } ]
		 *     },
		 *     {
		 *       "frameSizeX": 48,
		 *       "frameSizeY": 48,
		 *       "frames": [ { "x": 0, "y": 32, "ms": 100 }, { "x": 48, "y": 32, "ms": 100 }, { "x": 96, "y": 32, "ms": 100 }, { "x": 96, "y": 32, "ms": 100 }, { "x": 144, "y": 32, "ms": 100 }, { "x": 192, "y": 32, "ms": 100 } ]
		 *     },
		 *     {
		 *       "frameSizeX": 64,
		 *       "frameSizeY": 64,
		 *       "frames": [ { "x": 0, "y": 80, "ms": 100 }, { "x": 64, "y": 80, "ms": 100 }, { "x": 128, "y": 80, "ms": 100 }, { "x": 192, "y": 80, "ms": 100 }, { "x": 256, "y": 80, "ms": 100 }, { "x": 320, "y": 80, "ms": 100 } ]
		 *     }
		 *   ]
		 * }
		 * ```
		 * Here we load animation from image 'Atlas.png' (path relative to the json config), we load 3 animation each with 6 frames all have different frame size, x and y pairs is the left upper corner of each animation frame, the lower right corner is calculated based on frameSizeX and frameSizeY of each animation.
		 * @warning Each frame timing specified in ms in the config will be rounded to the nearest tick based on the tickrate, so for example if we have tickrate of 60 and our frame length is specified to be 110ms in the config it will be rounded to 7 ticks and that is 116.6...ms.
		 */
		class AnimationPack : public Profiling::Trackable<AnimationPack>, public std::enable_shared_from_this<AnimationPack>{
		public:
			/**
			 * @brief Available animation pack config types.
			 */
			enum ConfigType : uint8_t {
				ASEPRITE,
				CORI_UNIFORM,
				CORI_VARYING,
				INVALID
			};

			/**
			 * @brief AnimationPack Descriptor meant to be used with AssetManager only.
			 */
			class Descriptor {
			public:
				/**
				 * @brief Constructs a descriptor.
				 * @param name Name to be assigned to the AnimationPack.
				 * @param jsonPath Path to the json config file.
				 * @param type Type of the config file, specifies how the config file will be interpreted.
				 */
				constexpr Descriptor(std::string name, std::filesystem::path jsonPath, const ConfigType type) noexcept
					: m_JsonPath(std::move(jsonPath)),
					m_ConfigType(type),
					m_Name(std::move(name)),
					m_RuntimeID(s_NextRuntimeID.fetch_add(1, std::memory_order_relaxed))
				{ }

				using AssetType = AnimationPack;

				[[nodiscard]] uint32_t GetRuntimeID() const { return m_RuntimeID; }

				constexpr bool operator==(const Descriptor& other) const noexcept {
					return m_RuntimeID == other.m_RuntimeID;
				}

				struct Hasher {
					std::size_t operator()(const Descriptor& descriptor) const noexcept {
						return std::hash<uint32_t>{}(descriptor.m_RuntimeID);
					}
				};

				const std::filesystem::path m_JsonPath;
				const ConfigType m_ConfigType;
				const std::string m_Name;

			private:
				const uint32_t m_RuntimeID{ 0 };
				inline static std::atomic<uint32_t> s_NextRuntimeID{ 1 };
			};

			/**
			 * @brief Creates an AnimationPack.
			 * @param jsonPath Path to the config file.
			 * @param type Type of the config file, specifies how the config file will be interpreted.
			 * @param name Name to be assigned to the AnimationPack.
			 * @return Shared ptr with the created AnimationPack.
			 */
			[[nodiscard]] static std::shared_ptr<AnimationPack> Create(const std::filesystem::path& jsonPath, ConfigType type, const std::string& name);

			[[nodiscard]] Animation GetAnimation(const uint32_t index);

		protected:
			friend Animation;
			friend World::Components::Entity::QuadAnimator;
			std::vector<Internal::AnimationData> m_Animations;

			std::variant<std::shared_ptr<SpriteAtlas>, std::shared_ptr<Texture2D>> m_TextureOrAtlas;

		private:
			friend AssetManager;
			[[nodiscard]] static std::shared_ptr<AnimationPack> Create(const Descriptor& descriptor);
			std::string m_Name;
		protected:
			ConfigType m_Type;
		private:
			AnimationPack(std::vector<Internal::AnimationData> animations, const std::shared_ptr<SpriteAtlas>& spriteAtlas, std::string name, const ConfigType type);
			AnimationPack(std::vector<Internal::AnimationData> animations, const std::shared_ptr<Texture2D>& spriteAtlas, std::string name, const ConfigType type);

			AnimationPack();

			bool m_Valid = false;
		};
	}
}
