#ifndef GLOBAL_PCH
#define GLOBAL_PCH

#include <functional>
#include <memory>
#include <vector>
#include <unordered_map>
#include <unordered_set>
#include <array>
#include <algorithm>
#include <random>
#include <map>
#include <chrono>
#include <iostream>
#include <system_error>
#include <filesystem>
#include <string_view>
#include <cstdint>
#include <atomic>
#include <functional>
#include <compare>
#include <stdexcept>
#include <system_error>
#include <expected>
#include <typeinfo> 
#include <utility> 
#include <typeindex>
#include <type_traits>
#include <mutex>
#include <ctime>
#include <iomanip>
#include <sstream>
#include <ostream>
#include <thread>
#include <fstream>
#include <concepts>
#include <numeric>
#include <bit>
#include <any>
#include <variant>
#include <ranges>
#include <limits>
#define GLM_ENABLE_EXPERIMENTAL
#include <glm/glm.hpp>
#include <glm/gtx/io.hpp>
#include <glm/gtx/string_cast.hpp>
#include <imgui.h>
#include "../src/Core/Utility/Macros.hpp"
#include "../src/Core/Logger.hpp"
#include "../src/Profiling/TimeProfiler.hpp"
#include "../src/Core/Uuid.hpp"
#include "../src/Core/Error.hpp"

#endif