#pragma once
#include "SceneSystem/Scene.hpp"
#include "SceneSystem/Entity.hpp"
#include "Renderer/PrimitivePool.hpp"
#include "Core/Utility/Random.hpp"

namespace Cori {
	namespace Components {
		namespace Entity {

			/**
			 * @brief It's basicaly a uint32_t internaly and can be treated as one
			 */
			using PrimitiveID = Utils::StringHash;

			struct RenderGroup {
				RenderGroup() = default;
				RenderGroup(Cori::Scene* scene, Cori::Entity entity) : m_ParentScene(scene), m_ParentEntity(entity) {}
				~RenderGroup() {
					auto& quadPool = m_ParentScene->GetPoolForType<Graphics::QuadPrimitive>();
					for (auto& [index, type] : m_Primitives | std::views::values) {
						switch (type) {
						case Graphics::Quad:
							quadPool.InvalidatePrimitive(index);
							break;
						default: // add cases for other primitives later
							break;
						}
					}
				}

				/**
				 * @brief Creates primitive of the specified type and adds it to the corresponding pool
				 *
				 * @details This version creates a primitive with specified ID.
				 * Use it when you want to access this primitive later, or have explicit control of its validity lifetime (not actual instance lifetime).
				 *
				 * @tparam T primitive type
				 * @param descriptor descriptor of primitive type T
				 * @param id ID to be assigned to the primitive. You can use compile-time string hash like this: "Name"_hs, or a uint32_t.
				 * @return pointer to the created primitive
				 *
				 * @note Using compile-time string hash can possibly result in conflicts even when using different names because FNV-1a is used.
				 * This is pretty unlikely, but very much can happen.
				 */
				template <typename T> requires Utils::OneOf<T, Graphics::QuadPrimitive>
				T* AddPrimitive(const typename T::Descriptor& descriptor, const PrimitiveID id) {
					if (CORI_CORE_ASSERT_ERROR(!m_Primitives.contains(id), "Primitive with the specified name already exists in the hash map. ID: {}", id)) { return nullptr; }

					T primitive;
					// constexpr branch here for other primitive types
					primitive.m_WorldOrigin = m_WorldPosition;
					primitive.m_LocalPosition = descriptor.localPosition;
					primitive.m_Size = descriptor.size;
					primitive.m_TintColor = descriptor.tintColor;
					primitive.m_Owner = m_ParentEntity;
					primitive.SetUVs(descriptor.uvs);
					primitive.m_Rotation = descriptor.rotation;
					primitive.m_Layer = descriptor.layer;
					primitive.SetTexture(descriptor.texture);
					primitive.m_ID = id;

					auto [primPtr, index] = m_ParentScene->GetPoolForType<T>().AddPrimitive(primitive);
					primPtr->SetValidity(true);
					primPtr->SetVisibility(true);

					m_Primitives.insert({id, {index, Graphics::PrimitiveTypeTraits<T>::type}});

					return primPtr;
				}


				/**
				 * @brief Creates primitive of the specified type and adds it to the corresponding pool
				 *
				 * @details This version creates a primitive with autogenerated id (key for the hashmap),
				 * use it when you dont need to access the primitive after its creation.
				 *
				 * @tparam T primitive type
				 * @param descriptor descriptor of primitive type T
				 * @return pointer to the created primitive
				 *
				 * @note ID collisions are impossible if using only this version,
				 * but are theoretically possible if using version where you specify the ID as a compile-time string hash (or uint32_t if you prefer).
				 * Although it is possible, it is very unlikely, just don't create tens of thousands of primitives for one entity and you'll be fine.
				 */
				template <typename T> requires Utils::OneOf<T, Graphics::QuadPrimitive>
				T* AddPrimitive(const typename T::Descriptor& descriptor) {
					if (CORI_CORE_ASSERT_ERROR(!m_Primitives.contains(m_NextUnnamedIndex), "Autogenerated ID collision. ID: {}", m_NextUnnamedIndex)) { return nullptr; }
					m_NextUnnamedIndex--;
					return AddPrimitive<T>(descriptor, m_NextUnnamedIndex);
				}

				template <typename T> requires Utils::OneOf<T, Graphics::QuadPrimitive>
				std::expected<T*, const char*> GetPrimitive(const PrimitiveID id) {
					if (m_Primitives.contains(id)) {
						auto [index, type] = m_Primitives.at(id);
						if (Graphics::PrimitiveTypeTraits<T>::IsValid(type) != type) {
							return std::unexpected("Error: Specified primitive type doesnt match the type at the specified id.");
						}
						return m_ParentScene->GetPoolForType<T>().GetPrimitive(index);
					}
					return std::unexpected("Error: No primitive with the specified id found in the hashmap.");
				}



				/**
				 * @brief Invalidates the primitives with the specified id
				 *
				 * @details Invalid entities will not be rendered, handle to it will not exist in the hashmap, but id doesn't actually gets destroyed upon calling this.
				 * Invalid primitives will be fully destroyed from the memory upon the next Defragment() call for the corresponding pool.
				 *
				 * @param id
				 */
				void InvalidatePrimitive(const PrimitiveID id) {
					if (CORI_CORE_ASSERT_ERROR(m_Primitives.contains(id), "No primitive with the ID: {} was found in the hashmap. Nothing to invalidate", id)) { return; }
					auto& quadPool = m_ParentScene->GetPoolForType<Graphics::QuadPrimitive>();

					auto handle = m_Primitives[id];
					switch (handle.type) {
					case Graphics::Quad:
						quadPool.InvalidatePrimitive(handle.index);
						m_Primitives.erase(id);
						break;
					default: // add cases for other primitives later
						break;
					}
				}

				/**
				 * @brief
				 * @param position
				 */
				void SetWorldPosition(glm::vec2 position) {
					if (!m_Primitives.empty()) {
						auto& quadPool = m_ParentScene->GetPoolForType<Graphics::QuadPrimitive>();
						for (auto& [index, type] : m_Primitives | std::views::values) {
							switch (type) {
							case Graphics::Quad:
								quadPool.GetPrimitive(index)->m_WorldOrigin = position;
								break;
							default: // add cases for other primitives later
								break;
							}
						}
					}
					m_WorldPosition = position;
				}

				/**
				 * @brief
				 * @return Updated world position.
				 */
				glm::vec2 GetWorldPosition() const {
					return m_WorldPosition;
				}

			protected:
				template<typename Primitive> requires Utils::OneOf<Primitive, Graphics::QuadPrimitive>
				friend class Graphics::PrimitivePool;

				void UpdatePrimitiveIndex(const PrimitiveID id, uint32_t newIndex) {
					m_Primitives[id].index = newIndex;
				}

			private:

				std::unordered_map<PrimitiveID, Graphics::PrimitiveHandle> m_Primitives;
				PrimitiveID m_NextUnnamedIndex{ 0xFFFFFFFF };

				glm::vec2 m_WorldPosition{ 0.0f, 0.0f };

				Cori::Scene* m_ParentScene{nullptr};
				Cori::Entity m_ParentEntity;
			};

		}
	}
}