#ifndef GLOBALDEFINES_HPP
#define GLOBALDEFINES_HPP

#define CORI_MULTITHREADED_PHYSICS false
#define CORI_MAX_PHYSICS_THREADS 8
#define CORI_PHYSICS_TASK_POOL_SIZE 64
#define CORI_MAX_TRIGGER_VISITORS 2
//#define CORI_ASYNC_LOGGING
#define CORI_PIXELS_PER_METER 16
#define CORI_DISPOSABLE_ANIMATION_POOL_SIZE 32

#ifdef DEBUG_BUILD
	#define CORI_VMA_LEAK_INSTRUMENTATION
#endif

//#define CORI_VMA_VERBOSE_ALLOCATION_LOGGING

namespace Cori {
	static constexpr uint32_t s_PoisonValue{ 0xBAADF00D };
}

#endif
